import{a as S,S as v,i}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const q="51772163-3de497f859106760c35bf95d8",B="https://pixabay.com/api/";async function u(o,r){const n={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await S.get(B,{params:n})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const r=o.map(({webformatURL:n,largeImageURL:a,tags:e,likes:t,views:s,comments:b,downloads:w})=>`
      <a class="gallery-item" href="${a}">
        <img src="${n}" alt="${e}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${s}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${w}</p>
        </div>
      </a>`).join("");f.insertAdjacentHTML("beforeend",r),M.refresh()}function $(){f.innerHTML=""}function p(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function E(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}const O=document.querySelector("#search-form"),P=document.querySelector(".load-more");let l="",c=1,d=0;O.addEventListener("submit",T);P.addEventListener("click",H);async function T(o){if(o.preventDefault(),l=o.currentTarget.elements.searchQuery.value.trim(),c=1,!l){i.warning({message:"Please enter a search term!"});return}$(),L(),p();try{const r=await u(l,c);if(d=r.totalHits,r.hits.length===0){i.info({message:"No images found. Try another search."});return}y(r.hits),d>15&&E()}catch{i.error({message:"Something went wrong. Try again later."})}finally{g()}}async function H(){c+=1,p();try{const o=await u(l,c);y(o.hits),x(),c*15>=d&&(L(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({message:"Error loading more images."})}finally{g()}}function x(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
