import{a as q,S as B,i as n}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const M="51772163-3de497f859106760c35bf95d8",E="https://pixabay.com/api/";async function y(e,r){const o={key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await q.get(E,{params:o})).data}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),b=document.querySelector(".load-more"),O=new B(".gallery a",{captionsData:"alt",captionDelay:250});function L(e){const r=e.map(({webformatURL:o,largeImageURL:i,tags:t,likes:s,views:c,comments:S,downloads:$})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${o}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${s}</p>
          <p><b>Views:</b> ${c}</p>
          <p><b>Comments:</b> ${S}</p>
          <p><b>Downloads:</b> ${$}</p>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",r),O.refresh()}function P(){g.innerHTML=""}function w(){p.classList.remove("hidden")}function v(){p.classList.add("hidden")}function m(){b.classList.remove("hidden")}function l(){b.classList.add("hidden")}const H=document.querySelector("#search-form"),d=document.querySelector(".load-more");let h="",u=1,f=0,a=0;H.addEventListener("submit",N);d.addEventListener("click",T);async function N(e){e.preventDefault();const r=e.currentTarget.elements.searchQuery.value.trim();if(!r){n.warning({message:"Please enter a search term!"});return}h=r,u=1,a=0,P(),l(),w();try{const o=await y(h,u);if(f=Number(o.totalHits)||0,!o.hits||o.hits.length===0){n.info({message:"No images found. Try another search."});return}L(o.hits),a=o.hits.length,a<f?(m(),d.disabled=!1):(l(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch(o){n.error({message:`Something went wrong. ${(o==null?void 0:o.message)||""}`.trim()})}finally{v()}}async function T(){l(),d.disabled=!0,u+=1,w();try{const e=await y(h,u),r=(e==null?void 0:e.hits)||[];if(r.length===0){l(),n.info({message:"We're sorry, but you've reached the end of search results."});return}L(r),a+=r.length,x(),a<f?(m(),d.disabled=!1):(l(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch(e){n.error({message:`Error loading more images. ${(e==null?void 0:e.message)||""}`.trim()}),a<f&&(m(),d.disabled=!1)}finally{v()}}function x(){const e=document.querySelector(".gallery li");if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
